### ISSUE TITLE
Drop Make

### ISSUE THREAD

**Issue by rgaiacs** [wking/swc-setup-installation-test#10]
@wking Can we drop the `Make`? Sometimes people couldn't install `Make` on their Windows machines but almost never we cover `Make` at the workshops.

@jessicamizzi Do you want to add something?

**Comment by jessicalumian** [comment]
Mercurial only supports Python 2.4 to 2.7 [1], so that should be dropped if Python 3.5 is being used.  Is Mercurial used often in workshops?

[1] https://www.mercurial-scm.org/downloads

**Comment by wking** [comment]
On Sat, Nov 21, 2015 at 06:22:11PM -0800, Raniere Silva wrote:

> @wking Can we drop the `Make`?

I'd rather just land #9 and have:
- Workshop instructors list the lessons they'll cover [1](for each
  track if the workshop contains R and Python tracks, etc.).
- Lesson maintainers list their lesson's requirements [2](https://github.com/wking/swc-setup-installation-test/blob/lesson-dependencies/README.md#for-lesson-maintainers).

Then we don't have to define “the usual workshop”, which is a question
I have really terrible visibility into.  #9 will also make _all_
installation checks op-in, so we won't have this “I didn't want to
check for $X but forgot to remove that check” problem.
